#!/bin/sh
#
# Start Net TMP....
#


start() {
    ifconfig eth0 up 192.168.10.130 netmask 255.255.255.0
    route add default gw 192.168.10.1
}

case "$1" in
    start)
	start
	;;
  *)
	echo "Usage: $0 {start}"
	exit 1
esac

exit $?
